import Head from "next/head";
// import Script from "next/script";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 32px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js"></Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <div className={styles.imageWrap}>
          <Image
            className={styles.myImg}
            src={"/homeimg.avif"}
            width={237}
            height={158}
            alt="Not img found"
          />
        </div>
        <p className={styles.description}>
          A blog for Hunting Coders by a Hunting Coder
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn Node.Js in 2022?</h3>
            <p>Node.Js is the most popular backend language in this era.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn React.Js in 2022?</h3>
            <p>React.Js is the most popular JavaScript library in this era.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Next.Js in 2022?</h3>
            <p>Next.Js is the most popular React.Js Framework in this era.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
